name: code-checks

on: [push, pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-node@v2-beta
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Check size
        run: npm run size
