name: publish-to-npm

on:
  release:
    types: [published]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}
